local hl = vim.api.nvim_set_hl

return {
        hl( 0,  'TermCursor',       { fg = '#2EB398',   bg = 'NONE'     }),
        hl( 0,  'Cursor',           { fg = '#2EB398',   bg = 'NONE'     }),
        hl( 0,  'CursorIM',         { fg = '#2EB398',   bg = 'NONE'     }),
        hl( 0,  'lCursor',          { fg = '#2EB398',   bg = 'NONE'     }),
        hl( 0,  'Normal',           { fg = '#CCD7D4',   bg = '#141A1B'  }),
        hl( 0,  'LineNr',           { fg = '#2A3538',   bg = 'NONE'     }),
        hl( 0,  'NonText',          { fg = '#2A3538',   bg = '#141A1B'  }),
        hl( 0,  'EndOfBuffer',      { fg = '#141A1B',   bg = 'NONE'     }),
        hl( 0,  'CursorLine',       { fg = 'NONE',      bg = '#1B2224'  }),
        hl( 0,  'CursorLineNr',     { fg = '#2EB398',   bg = 'NONE'     }),
        hl( 0,  'CursorColumn',     { fg = 'NONE',      bg = '#1B2224'  }),
        hl( 0,  'SignColumn',       { fg = 'NONE',      bg = 'NONE'     }),
        hl( 0,  'Folded',           { fg = '#141A1B',   bg = '#2A3538'  }),
        hl( 0,  'CursorLineFold',   { fg = '#2EB398',   bg = '#141A1B'  }),
        hl( 0,  'FoldColumn',       { fg = '#2A3538',   bg = '#141A1B'  }),
        hl( 0,  'WinSeparator',     { fg = '#2A3538',   bg = '#141A1B'  }),
        hl( 0,  'ColorColumn',      { fg = '#141A1B',   bg = '#1B2224'  }),
        hl( 0,  'Conceal',          { fg = '#2A3538',   bg = '#141A1B'  }),
        hl( 0,  'Visual',           { fg = 'NONE',      bg = '#222B2E'  }),
        hl( 0,  'DiffAdd',          { fg = '#141A1B',   bg = '#73C48F'  }),
        hl( 0,  'DiffChange',       { fg = '#141A1B',   bg = '#7AA2F7'  }),
        hl( 0,  'DiffDelete',       { fg = '#141A1B',   bg = '#D7787D'  }),
        hl( 0,  'DiffText',         { fg = '#141A1B',   bg = '#BB9AF7'  }),
        hl( 0,  'Added',            { fg = '#73C48F',   bg = '#141A1B'  }),
        hl( 0,  'Changed',          { fg = '#7AA2F7',   bg = '#141A1B'  }),
        hl( 0,  'Removed',          { fg = '#D7787D',   bg = '#141A1B'  }),
        hl( 0,  'Search',           { fg = 'NONE',      bg = '#454f4C'  }),
        hl( 0,  'CurSearch',        { fg = 'NONE',      bg = '#454f4C'  }),
        hl( 0,  'WarningMsg',       { fg = '#FF793E',   bg = 'NONE'     }),
        hl( 0,  'ErrorMsg',         { fg = '#D7787D',   bg = 'NONE'     }),
        hl( 0,  'Question',         { fg = '#2EB398',   bg = 'NONE'     }),
        hl( 0,  'ModeMsg',          { fg = '#141A1B',   bg = 'NONE'     }),
        hl( 0,  'MoreMsg',          { fg = '#454f4C',   bg = 'NONE'     }),
        hl( 0,  'Pmenu',            { fg = '#2EB398',   bg = '#1B2224'  }),
        hl( 0,  'PmenuSel',         { fg = '#141A1B',   bg = '#2EB398'  }),
        hl( 0,  'PmenuThumb',       { fg = 'NONE',      bg = '#141A1B'  }),
        hl( 0,  'PmenuSbar',        { fg = 'NONE',      bg = '#454f4C'  }),
        hl( 0,  'Directory',        { fg = '#2EB398',   bg = 'NONE',    bold = true     }),
        hl( 0,  'Comment',          { fg = '#454f4C',   bg = 'NONE',    italic = true   }),
        hl( 0,  'String',           { fg = '#E0AF68',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Character',        { fg = '#E0AF68',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Boolean',          { fg = '#6A7CE0',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Number',           { fg = '#BB9AF7',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Constant',         { fg = '#E0AF68',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Identifier',       { fg = '#CCD7D4',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Statement',        { fg = '#BB9AF7',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Function',         { fg = '#7AA2F7',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Operator',         { fg = '#7AA2F7',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Delimiter',        { fg = '#7AA2F7',   bg = 'NONE',    bold = false    }),
        hl( 0,  'Type',             { fg = '#2EB398',   bg = 'NONE',    bold = false    }),
        hl( 0,  '@variable',        { fg = '#CCD7D4',   bg = 'NONE',    bold = false    }),
}
